#%RAML 1.0
title: CSO2 Inventory Service
description: The inventory's service API, meant to be used internally.
version: 0.1.0

types:
  UserInventoryItem: !include types/UserInventoryItem.raml
  UserInventory: !include types/UserInventory.raml
  UserCosmetics: !include types/UserCosmetics.raml
  UserLoadout: !include types/UserLoadout.raml
  UserBuyMenu: !include types/UserBuyMenu.raml

resourceTypes:
  crudresource: !include resourceTypes/crudresource.raml
  udonly: !include resourceTypes/udonly.raml
  uidcollection: !include resourceTypes/uidcollection.raml

/inventory/{userId}:
  description: The inventory's API base
  uriParameters:
    userId:
      type: integer
      description: The user's ID number.
  type:
    uidcollection:
      uidColItemTypeName: UserInventory
  /item:
    type:
      udonly:
        udItemTypeName: UserInventoryItem
        udUidName: User
  /cosmetics:
    description: Manages an user's equipped cosmetic items.
    type:
      crudresource:
        resTypeName: UserCosmetics
  /loadout:
    description: Manages an user's weapon loadouts.
    type:
      crudresource:
        resTypeName: UserLoadout
  /buymenu:    
    description: Manages an user's weapons buy menu.
    type:
      crudresource:
        resTypeName: UserBuyMenu
/ping:
  get:
    description: Checks if a service is running.
    responses:
      200:
        description: The service is up and running.
      500:
        description: An internal error has occured.